import type { DomainSchemaName } from '../src/domain/domain-contract-registry.js'

const tenantId = 'tenant_s1'
const missionId = 'mission_s1'
const createdAt = '2026-01-01T00:00:00.000Z'
const laterAt = '2026-01-01T00:01:00.000Z'
const digestA = 'a'.repeat(64)
const digestB = 'b'.repeat(64)
const actor = { kind: 'system', id: 'system_s1' }
const scope = { environment: 'synthetic', system: 'legacy', entity: 'legacy_patient' }
const content = {
  uri: 'artifact://s1/source',
  sha256: digestA,
  mediaType: 'application/json',
  bytes: 128,
  span: { kind: 'whole' }
}
const budget = {
  tokenLimit: 10_000,
  timeLimitMs: 60_000,
  toolCallLimit: 10,
  outputByteLimit: 1_000_000,
  costLimitUsd: 10
}
const usage = {
  inputTokens: 10,
  outputTokens: 5,
  cacheReadTokens: 0,
  cacheWriteTokens: 0,
  toolCalls: 1,
  wallTimeMs: 100,
  costUsd: 0.01
}
const modelRoute = {
  provider: 'test',
  model: 'deterministic',
  revision: 'v1',
  effort: 'lo',
  dataClasses: ['synthetic']
}
const tool = {
  name: 'evidence_read',
  version: '1',
  schemaDigest: digestA,
  approval: 'read'
}
const independence = {
  producerMayEvaluate: false,
  process: 'different-required',
  model: 'not-applicable',
  provider: 'not-applicable',
  context: 'independent-required',
  credentials: 'not-applicable',
  producerReasoningVisible: false
}
const measureDefinition = {
  name: 'schema_valid',
  valueType: 'boolean',
  unit: '',
  hard: true,
  required: true,
  operator: 'eq',
  threshold: true,
  description: 'Subject matches the required schema.'
}
const evaluationSubjectV1 = {
  kind: 'mapping',
  id: 'artifact_s1',
  version: 1,
  schemaVersion: 1,
  digest: digestA
}
const target = {
  provider: 'fixture',
  account: 'synthetic',
  project: null,
  region: null,
  resourceType: 'profile',
  resourceId: 'legacy_patient'
}

export const DOMAIN_CONTRACT_SAMPLES: Record<DomainSchemaName, unknown> = {
  'mission-record.v1': {
    schemaVersion: 1,
    kind: 'mission',
    id: missionId,
    tenantId,
    missionId,
    revision: 0,
    objective: 'Produce an evidence-correct identity mapping.',
    priorities: ['correctness'],
    dataClass: 'synthetic',
    state: { status: 'investigating', enteredAt: createdAt },
    currentPlanRevisionId: null,
    labels: { slice: 's1' },
    createdAt,
    updatedAt: createdAt
  },
  'mission-command.v1': {
    schemaVersion: 1,
    kind: 'mission-command',
    id: 'command_s1',
    tenantId,
    missionId,
    expectedRevision: null,
    commandType: 'create-mission',
    payload: { objective: 'Produce an evidence-correct identity mapping.' },
    payloadSchema: { name: 'mission-create.v1', version: 1, digest: digestA },
    payloadDigest: digestA,
    actor,
    correlationId: 'correlation_s1',
    issuedAt: createdAt
  },
  'mission-event.v1': {
    schemaVersion: 1,
    kind: 'mission-event',
    id: 'event_s1',
    tenantId,
    missionId,
    aggregateRevision: 1,
    eventType: 'mission-created',
    payload: { objective: 'Produce an evidence-correct identity mapping.' },
    payloadSchema: { name: 'mission-created.v1', version: 1, digest: digestA },
    payloadDigest: digestA,
    actor,
    causationCommandId: 'command_s1',
    correlationId: 'correlation_s1',
    recordedAt: createdAt
  },
  'evidence-item.v1': {
    schemaVersion: 1,
    kind: 'evidence-item',
    id: 'evidence_s1',
    tenantId,
    missionId,
    createdAt,
    version: 1,
    sourceRole: 'direct-observation',
    sourceName: 'Synthetic key profile',
    sourceVersion: '1',
    content,
    scope,
    dataClass: 'synthetic',
    observedAt: createdAt,
    effectiveFrom: createdAt,
    effectiveUntil: null,
    supersedesEvidenceId: null,
    limitations: ['Six synthetic rows.']
  },
  'proposition.v1': {
    schemaVersion: 1,
    kind: 'proposition',
    id: 'proposition_s1',
    tenantId,
    missionId,
    createdAt,
    revision: 0,
    subject: 'legacy_patient',
    predicate: 'has-unique-key',
    object: ['facility_id', 'patient_num'],
    normalizedStatement: 'facility_id plus patient_num is unique.',
    scope,
    effectiveFrom: createdAt,
    effectiveUntil: null,
    supersedesPropositionId: null
  },
  'assertion.v1': {
    schemaVersion: 1,
    kind: 'assertion',
    id: 'assertion_s1',
    tenantId,
    missionId,
    createdAt,
    propositionId: 'proposition_s1',
    evidenceId: 'evidence_s1',
    polarity: 'supports',
    directness: 'direct',
    applicability: 'in-scope',
    derivationAssertionIds: [],
    rationale: 'Observed 6 distinct composite values over 6 rows.',
    assertedBy: actor
  },
  'contradiction-set.v1': {
    schemaVersion: 1,
    kind: 'contradiction-set',
    id: 'contradiction_s1',
    tenantId,
    missionId,
    createdAt,
    propositionIds: ['proposition_s1'],
    assertionIds: ['assertion_s1', 'assertion_s2'],
    blockingGapIds: ['gap_s1'],
    state: { status: 'open' }
  },
  'gap.v1': {
    schemaVersion: 1,
    kind: 'gap',
    id: 'gap_s1',
    tenantId,
    missionId,
    createdAt,
    revision: 0,
    question: 'Which source columns form a stable unique patient key?',
    impact: 'critical',
    propositionIds: ['proposition_s1'],
    hypothesisIds: [],
    contradictionIds: ['contradiction_s1'],
    probeCandidateIds: ['probe_s1'],
    blockedDecisionIds: ['decision_s1'],
    state: { status: 'investigating', reason: 'Conflicting design and profile evidence.' }
  },
  'probe-request.v1': {
    schemaVersion: 1,
    kind: 'probe-request',
    id: 'probe_s1',
    tenantId,
    missionId,
    createdAt,
    gapId: 'gap_s1',
    method: 'check_candidate_key',
    question: 'Is the composite key unique?',
    parameters: { columns: ['facility_id', 'patient_num'] },
    expectedEvidenceDigest: digestA,
    predictedOutcomes: [true, false],
    budget: { timeLimitMs: 10_000, rowLimit: 100, byteLimit: 1_000_000 },
    requestedBy: actor
  },
  'probe-result.v1': {
    schemaVersion: 1,
    kind: 'probe-result',
    id: 'probe_result_s1',
    tenantId,
    missionId,
    createdAt,
    requestId: 'probe_s1',
    inputDigest: digestA,
    outcome: {
      status: 'succeeded',
      observations: [{ distinct: 6, rows: 6 }],
      evidenceId: 'evidence_s1'
    },
    startedAt: createdAt,
    completedAt: laterAt,
    executedBy: actor
  },
  'accepted-finding.v1': {
    schemaVersion: 1,
    kind: 'accepted-finding',
    id: 'finding_s1',
    tenantId,
    missionId,
    createdAt,
    revision: 0,
    propositionId: 'proposition_s1',
    assertionIds: ['assertion_s1'],
    evidenceIds: ['evidence_s1'],
    probeResultIds: ['probe_result_s1'],
    scope,
    conclusion: 'The composite key is unique for the current fixture.',
    limitations: ['Synthetic fixture only.'],
    reversalConditions: ['A counterexample or changed profile appears.'],
    validFrom: createdAt,
    supersedesFindingId: null,
    acceptedBy: actor
  },
  'impact-review.v1': {
    schemaVersion: 1,
    kind: 'impact-review',
    id: 'impact_s1',
    tenantId,
    missionId,
    createdAt,
    triggerEvidenceIds: ['evidence_s1'],
    triggerFindingIds: ['finding_s1'],
    affectedRecordIds: ['decision_s1', 'artifact_version_s1'],
    disposition: 'reevaluate',
    rationale: 'The identity mapping depends on the key finding.',
    reviewedBy: actor
  },
  'decision-record.v1': {
    schemaVersion: 1,
    kind: 'decision-record',
    id: 'decision_s1',
    tenantId,
    missionId,
    createdAt,
    revision: 0,
    baseMissionRevision: 1,
    question: 'Select the source identity key.',
    options: [
      {
        id: 'single',
        label: 'Single key',
        description: 'patient_num only',
        tradeoffs: ['Not unique.']
      },
      {
        id: 'composite',
        label: 'Composite key',
        description: 'facility plus patient',
        tradeoffs: ['Wider key.']
      }
    ],
    selectedOptionId: 'composite',
    evidenceIds: ['evidence_s1'],
    assertionIds: ['assertion_s1'],
    findingIds: ['finding_s1'],
    probeResultIds: ['probe_result_s1'],
    assumptions: ['Fixture profile represents current scope.'],
    impactRecordIds: ['artifact_s1'],
    reversalConditions: ['Profile changes or a counterexample appears.'],
    rationale: 'Only the composite candidate is observed unique.',
    decidedBy: actor
  },
  'plan-revision.v1': {
    schemaVersion: 1,
    kind: 'plan-revision',
    id: 'plan_s1',
    tenantId,
    missionId,
    createdAt,
    revision: 1,
    basePlanRevisionId: null,
    baseMissionRevision: 1,
    operations: [
      {
        operation: 'add-task',
        taskId: 'task_s1',
        title: 'Build the identity mapping.',
        capability: 'identity-mapping',
        dependencyTaskIds: [],
        proofObligations: ['Pass the identity mapping evaluation contract.'],
        recoveryPolicy: {
          onWorkerLoss: 'reconstruct',
          onStaleResult: 'reject-authority-retain-evidence',
          maxAttempts: 2,
          requiresEvaluation: true
        }
      }
    ],
    decisionIds: ['decision_s1'],
    evidenceIds: ['evidence_s1'],
    findingIds: ['finding_s1'],
    rationale: 'Create one evaluated mapping task.',
    createdBy: actor,
    committedAt: createdAt
  },
  'task-record.v1': {
    schemaVersion: 1,
    kind: 'task',
    id: 'task_s1',
    tenantId,
    missionId,
    createdAt,
    revision: 0,
    planRevisionId: 'plan_s1',
    title: 'Build the identity mapping.',
    capability: 'identity-mapping',
    dependencyTaskIds: [],
    proofObligations: ['Pass all hard mapping measures.'],
    requiredEvaluationContractIds: ['evaluation_contract_s1'],
    ownedScope: [scope],
    readScope: [scope],
    budget,
    recoveryPolicy: {
      onWorkerLoss: 'reconstruct',
      onStaleResult: 'reject-authority-retain-evidence',
      maxAttempts: 2,
      requiresEvaluation: true
    },
    state: { status: 'runnable' }
  },
  'context-manifest.v1': {
    schemaVersion: 1,
    kind: 'context-manifest',
    id: 'context_s1',
    tenantId,
    missionId,
    createdAt,
    assignmentId: 'assignment_s1',
    attemptId: 'attempt_s1',
    baseMissionRevision: 1,
    role: 's1-profile-artifact-engineer',
    strategyVersion: 'exact-v1',
    modelRoute,
    budget,
    items: [
      {
        itemId: 'context_item_1',
        evidenceId: 'evidence_s1',
        evidenceVersion: 1,
        evidenceDigest: digestA,
        span: { kind: 'whole' },
        sourceRole: 'direct-observation',
        dataClass: 'synthetic',
        position: 0,
        trust: 'direct',
        freshness: 'current'
      }
    ],
    excludedEvidence: [],
    redactions: [],
    systemPromptDigest: digestA,
    toolSetDigest: digestA,
    outputSchemaDigest: digestA,
    renderedContextDigest: digestA,
    compiledBy: actor
  },
  'corpus-source-manifest.v1': {
    schemaVersion: 1,
    kind: 'corpus-source-manifest',
    id: 'corpus_manifest_s1',
    tenantId,
    createdAt,
    sourceId: 'corpus_source_s1',
    version: 1,
    sourceVersion: 'v1',
    sourceClass: 'reference',
    visibility: 'tenant',
    owner: { kind: 'vendor', id: 'vendor_s1', name: 'Fixture Vendor' },
    permission: {
      basis: 'licensed',
      licenseId: 'MIT',
      termsUri: null,
      ingestAllowed: true,
      renderAllowed: true,
      derivativeAllowed: true
    },
    canonicalUri: 'source://s1/reference',
    title: 'Synthetic source reference',
    publisher: 'Fixture Vendor',
    content: { ...content, uri: `corpus-object://sha256/${digestA}` },
    dataClass: 'synthetic',
    applicability: {
      scope,
      product: 'fixture',
      versionConstraint: 'v1',
      effectiveFrom: createdAt,
      effectiveUntil: null
    },
    observedAt: createdAt,
    sourcePublishedAt: createdAt,
    freshness: { kind: 'immutable', staleDisposition: 'never-stale' },
    retention: { retainUntil: null, deletionMode: 'retain', policyId: 'fixture-retention' },
    supersedesManifestId: null,
    limitations: ['Synthetic fixture only.'],
    registeredBy: actor
  },
  'corpus-parse-version.v1': {
    schemaVersion: 1,
    kind: 'corpus-parse-version',
    id: 'corpus_parse_s1',
    tenantId,
    createdAt,
    sourceManifestId: 'corpus_manifest_s1',
    sourceId: 'corpus_source_s1',
    sourceVersion: 1,
    sourceDigest: digestA,
    parser: { name: 'fixture-parser', version: '1', implementationDigest: digestB },
    output: { ...content, uri: 'artifact://s1/parsed', sha256: digestB },
    warnings: [],
    parsedBy: actor
  },
  'corpus-chunk.v1': {
    schemaVersion: 1,
    kind: 'corpus-chunk',
    id: 'corpus_chunk_s1',
    tenantId,
    createdAt,
    sourceManifestId: 'corpus_manifest_s1',
    parseVersionId: 'corpus_parse_s1',
    ordinal: 0,
    chunkType: 'document',
    content: 'patient_num repeats across facilities',
    contentDigest: digestA,
    sourceSpan: { kind: 'text-lines', startLine: 1, endLine: 1 },
    mediaType: 'text/plain',
    tokenEstimate: 8,
    sourceRole: 'external-reference',
    dataClass: 'synthetic',
    applicability: {
      scope,
      product: 'fixture',
      versionConstraint: 'v1',
      effectiveFrom: createdAt,
      effectiveUntil: null
    },
    entityKeys: ['legacy_patient.patient_num']
  },
  'corpus-entity.v1': {
    schemaVersion: 1,
    kind: 'corpus-entity',
    id: 'corpus_entity_s1',
    tenantId,
    createdAt,
    entityType: 'column',
    canonicalKey: 'legacy_patient.patient_num',
    displayName: 'patient_num',
    attributes: { nullable: false },
    provenanceChunkIds: ['corpus_chunk_s1']
  },
  'corpus-relation.v1': {
    schemaVersion: 1,
    kind: 'corpus-relation',
    id: 'corpus_relation_s1',
    tenantId,
    createdAt,
    fromEntityId: 'corpus_entity_s1',
    toEntityId: 'corpus_entity_target',
    relationType: 'maps-to',
    directed: true,
    attributes: { confidence: 'observed' },
    provenanceChunkIds: ['corpus_chunk_s1']
  },
  'assignment-record.v1': {
    schemaVersion: 1,
    kind: 'assignment',
    id: 'assignment_s1',
    tenantId,
    missionId,
    createdAt,
    revision: 0,
    taskId: 'task_s1',
    role: 's1-profile-artifact-engineer',
    contractVersion: 1,
    contextManifestId: 'context_s1',
    tools: [tool],
    outputSchema: { name: 'identity-mapping.v1', version: 1, digest: digestA, mode: 'strict' },
    modelRoute,
    budget,
    spawnPolicy: { enabled: false, maxDepth: 0, allowedRoles: [] },
    requiredEvaluationContractIds: ['evaluation_contract_s1'],
    state: { status: 'created' },
    assignedBy: actor
  },
  'assignment-attempt.v1': {
    schemaVersion: 1,
    kind: 'assignment-attempt',
    id: 'attempt_s1',
    tenantId,
    missionId,
    createdAt,
    assignmentId: 'assignment_s1',
    attemptNumber: 1,
    fence: 1,
    worker: {
      runtime: 'deterministic-runner',
      runtimeVersion: '1',
      protocolVersion: '1',
      processIncarnation: 'process_s1',
      sessionRef: null
    },
    contextManifestId: 'context_s1',
    state: { status: 'running', leaseExpiresAt: laterAt },
    startedAt: createdAt
  },
  'assignment-result.v1': {
    schemaVersion: 1,
    kind: 'assignment-result',
    id: 'assignment_result_s1',
    tenantId,
    missionId,
    createdAt,
    assignmentId: 'assignment_s1',
    attemptId: 'attempt_s1',
    fence: 1,
    outputDigest: digestA,
    outcome: {
      status: 'succeeded',
      artifactVersionIds: ['artifact_version_s1'],
      evidenceIds: ['evidence_s1'],
      gapIds: [],
      planRevisionIds: ['plan_s1']
    },
    usage,
    limitations: ['Synthetic fixture only.'],
    submittedAt: laterAt,
    submittedBy: actor
  },
  'artifact-version.v1': {
    schemaVersion: 1,
    kind: 'artifact-version',
    id: 'artifact_version_s1',
    tenantId,
    missionId,
    createdAt,
    artifactId: 'artifact_s1',
    artifactType: 'mapping',
    version: 1,
    previousVersionId: null,
    content,
    producerAssignmentId: 'assignment_s1',
    producerAttemptId: 'attempt_s1',
    producerFence: 1,
    decisionIds: ['decision_s1'],
    evidenceIds: ['evidence_s1'],
    state: { status: 'proposed' }
  },
  'evaluator-definition.v1': {
    schemaVersion: 1,
    kind: 'evaluator-definition',
    id: 'evaluator_s1',
    tenantId,
    createdAt,
    version: 1,
    evaluatorType: 'deterministic',
    implementation: content,
    supportedSubjectKinds: ['mapping'],
    supportedSubjectSchemaVersions: [1],
    requiredTools: [],
    independence,
    measures: [measureDefinition],
    calibrationCorpus: null,
    knownLimitations: ['Synthetic identity fixture only.'],
    budget,
    revokedAt: null
  },
  'evaluation-contract.v1': {
    schemaVersion: 1,
    kind: 'evaluation-contract',
    id: 'evaluation_contract_s1',
    tenantId,
    createdAt,
    version: 1,
    subjectKind: 'mapping',
    subjectSchemaVersion: 1,
    measures: [{ ...measureDefinition, evaluatorId: 'evaluator_s1', evaluatorVersion: 1 }],
    composition: 'all',
    independence,
    maxAgeMs: 60_000,
    correctionBudget: 2,
    unavailableDisposition: 'unaccepted',
    contradictoryDisposition: 'quarantined',
    revokedAt: null
  },
  'evaluation-assignment.v1': {
    schemaVersion: 1,
    kind: 'evaluation-assignment',
    id: 'evaluation_assignment_s1',
    tenantId,
    missionId,
    createdAt,
    contractId: 'evaluation_contract_s1',
    contractVersion: 1,
    evaluatorId: 'evaluator_s1',
    evaluatorVersion: 1,
    subject: evaluationSubjectV1,
    contextManifestId: 'context_s1',
    inputEvidenceIds: ['evidence_s1'],
    producer: { actor, assignmentId: 'assignment_s1', attemptId: 'attempt_s1', fence: 1 },
    evaluatorAttemptId: 'attempt_eval',
    evaluatorFence: 1,
    deadlineAt: laterAt,
    budget
  },
  'evaluation-result.v1': {
    schemaVersion: 1,
    kind: 'evaluation-result',
    id: 'evaluation_result_s1',
    tenantId,
    missionId,
    createdAt,
    assignmentId: 'evaluation_assignment_s1',
    contractId: 'evaluation_contract_s1',
    contractVersion: 1,
    evaluatorId: 'evaluator_s1',
    evaluatorVersion: 1,
    subject: evaluationSubjectV1,
    status: 'passed',
    measures: [
      {
        name: 'schema_valid',
        status: 'pass',
        value: true,
        threshold: true,
        evidenceIds: ['evidence_s1'],
        failureCode: null
      }
    ],
    coverage: 'complete',
    evidenceIds: ['evidence_s1'],
    limitations: ['Synthetic fixture only.'],
    usage,
    completedAt: laterAt,
    resultDigest: digestA
  },
  'correction-request.v1': {
    schemaVersion: 1,
    kind: 'correction-request',
    id: 'correction_request_s1',
    tenantId,
    missionId,
    createdAt,
    failedSubject: evaluationSubjectV1,
    evaluationResultIds: ['evaluation_result_failed'],
    failedMeasureNames: ['source_key_unique'],
    gapIds: ['gap_s1'],
    allowedMutationPaths: ['/sourceKey'],
    acceptanceContractId: 'evaluation_contract_s1',
    acceptanceContractVersion: 1,
    attempt: 1,
    maxAttempts: 2,
    requestedBy: actor
  },
  'correction-result.v1': {
    schemaVersion: 1,
    kind: 'correction-result',
    id: 'correction_result_s1',
    tenantId,
    missionId,
    createdAt,
    requestId: 'correction_request_s1',
    priorSubject: evaluationSubjectV1,
    newSubject: { ...evaluationSubjectV1, version: 2, digest: digestB },
    changedPaths: ['/sourceKey'],
    evidenceIds: ['evidence_s1'],
    unresolvedGapIds: [],
    acceptanceContractId: 'evaluation_contract_s1',
    acceptanceContractVersion: 1,
    usage,
    completedAt: laterAt,
    producedBy: actor
  },
  'learning-candidate.v1': {
    schemaVersion: 1,
    kind: 'learning-candidate',
    id: 'learning_s1',
    tenantId,
    missionId,
    createdAt,
    candidateType: 'memory',
    sourceEvaluationResultIds: ['evaluation_result_s1'],
    sourceEvidenceIds: ['evidence_s1'],
    sourceRecordIds: ['correction_request_s1', 'artifact_s1'],
    causalHypothesis: 'Declared identifiers require observed uniqueness verification.',
    proposedArtifact: content,
    targetEnvelope: {
      taskClasses: ['identity-mapping'],
      modelRoutes: [],
      dataClasses: ['synthetic'],
      environment: 'prototype'
    },
    allowedMutationPaths: ['/memory/failure-lessons'],
    authorityDelta: 'none',
    retentionExpiresAt: null,
    state: { status: 'quarantined', usePolicy: 'none', validationStatus: 'not-run' },
    proposedBy: actor
  },
  'capability-manifest.v1': {
    schemaVersion: 1,
    kind: 'capability-manifest',
    id: 'capability_s1',
    tenantId,
    createdAt,
    version: 1,
    capabilityType: 'skill',
    artifact: content,
    contract: { inputSchemaId: 'input.v1', outputSchemaId: 'output.v1', schemaDigest: digestA },
    compatibleModelRoutes: [modelRoute],
    requiredTools: [tool],
    dataClasses: ['synthetic'],
    authorityEnvelope: {},
    evaluationContractIds: ['evaluation_contract_s1'],
    predecessorCapabilityId: null,
    license: 'MIT',
    signer: null,
    status: { status: 'certified', certificationId: 'certification_s1' }
  },
  'certification-result.v1': {
    schemaVersion: 1,
    kind: 'certification-result',
    id: 'certification_s1',
    tenantId,
    createdAt,
    capabilityId: 'capability_s1',
    capabilityVersion: 1,
    baselineCapabilityId: null,
    evaluationResultIds: ['evaluation_result_s1'],
    measures: [
      {
        name: 'schema_valid',
        status: 'pass',
        value: true,
        threshold: true,
        evidenceIds: ['evidence_s1'],
        failureCode: null
      }
    ],
    protectedSliceResults: { synthetic: 'pass' },
    repetitions: 1,
    status: 'passed',
    limitations: [],
    completedAt: laterAt
  },
  'promotion-decision.v1': {
    schemaVersion: 1,
    kind: 'promotion-decision',
    id: 'promotion_s1',
    tenantId,
    createdAt,
    capabilityId: 'capability_s1',
    capabilityVersion: 1,
    certificationId: 'certification_s1',
    stableCapabilityId: null,
    stage: 'shadow',
    trafficLimitPercent: 0,
    taskLimit: 10,
    timeLimitMs: 60_000,
    abortConditions: ['Any hard evaluator failure.'],
    decidedBy: actor
  },
  'capability-use.v1': {
    schemaVersion: 1,
    kind: 'capability-use',
    id: 'capability_use_s1',
    tenantId,
    missionId,
    createdAt,
    capabilityId: 'capability_s1',
    capabilityVersion: 1,
    assignmentId: 'assignment_s1',
    attemptId: 'attempt_s1',
    modelRoute,
    inputDigest: digestA,
    outputDigest: digestB,
    evaluationResultIds: ['evaluation_result_s1'],
    outcome: 'unknown',
    usage
  },
  'drift-signal.v1': {
    schemaVersion: 1,
    kind: 'drift-signal',
    id: 'drift_s1',
    tenantId,
    createdAt,
    capabilityId: 'capability_s1',
    capabilityVersion: 1,
    windowStartedAt: createdAt,
    windowEndedAt: laterAt,
    baselineDigest: digestA,
    measures: [
      {
        name: 'schema_valid',
        status: 'pass',
        value: true,
        threshold: true,
        evidenceIds: ['evidence_s1'],
        failureCode: null
      }
    ],
    affectedUseIds: ['capability_use_s1'],
    severity: 'info',
    action: 'observe',
    detectedBy: actor
  },
  'effect-intent.v1': {
    schemaVersion: 1,
    kind: 'effect-intent',
    id: 'effect_s1',
    tenantId,
    missionId,
    createdAt,
    operationClass: 'pure-read',
    adapter: { name: 'fixture', version: '1', method: 'read-profile' },
    target,
    parameters: { entity: 'legacy_patient' },
    parameterDigest: digestA,
    expectedPreState: {},
    desiredPostState: {},
    expectedTargetVersion: null,
    idempotency: {
      kind: 'none',
      key: null,
      retentionExpiresAt: null,
      parameterDigest: digestA
    },
    requiredTools: [tool],
    allowedNetworkDestinations: [],
    requiredSecretScopes: [],
    dataClasses: ['synthetic'],
    budget,
    reversible: false,
    compensationId: null,
    evaluatorContractIds: ['evaluation_contract_s1'],
    evidenceRecordIds: ['evidence_s1'],
    proposedBy: actor
  },
  'policy-decision.v1': {
    schemaVersion: 1,
    kind: 'policy-decision',
    id: 'policy_s1',
    tenantId,
    missionId,
    createdAt,
    effectId: 'effect_s1',
    intentDigest: digestA,
    policyBundleVersion: '1',
    policyBundleDigest: digestA,
    structuredInputDigest: digestA,
    decision: 'allow',
    grant: {
      target,
      adapterName: 'fixture',
      adapterMethod: 'read-profile',
      parameterDigest: digestA,
      toolNames: ['evidence_read'],
      networkDestinations: [],
      secretScopes: [],
      maxUses: 1,
      expiresAt: laterAt
    },
    obligations: ['Record evidence digest.'],
    ruleIds: ['synthetic-read'],
    reasons: ['Synthetic read-only fixture.'],
    decidedBy: actor,
    expiresAt: laterAt
  },
  'secret-lease.v1': {
    schemaVersion: 1,
    kind: 'secret-lease',
    id: 'secret_lease_s1',
    tenantId,
    missionId,
    createdAt,
    effectId: 'effect_s1',
    secretReference: 'secret://synthetic/none',
    recipient: {
      assignmentId: 'assignment_s1',
      attemptId: 'attempt_s1',
      fence: 1,
      audience: 'fixture-adapter'
    },
    target,
    scopes: ['read'],
    issuedAt: createdAt,
    expiresAt: laterAt,
    maxUses: 1,
    revokedAt: null
  },
  'capability-envelope.v1': {
    schemaVersion: 1,
    kind: 'capability-envelope',
    id: 'envelope_s1',
    tenantId,
    missionId,
    createdAt,
    effectId: 'effect_s1',
    intentDigest: digestA,
    policyDecisionId: 'policy_s1',
    workload: {
      assignmentId: 'assignment_s1',
      attemptId: 'attempt_s1',
      fence: 1,
      audience: 'fixture-adapter'
    },
    target,
    adapterName: 'fixture',
    adapterMethod: 'read-profile',
    parameterDigest: digestA,
    allowedTools: [tool],
    allowedNetworkDestinations: [],
    dataClasses: ['synthetic'],
    secretLeaseIds: ['secret_lease_s1'],
    budget,
    maxUses: 1,
    issuedAt: createdAt,
    expiresAt: laterAt,
    revokedAt: null
  },
  'effect-attempt.v1': {
    schemaVersion: 1,
    kind: 'effect-attempt',
    id: 'effect_attempt_s1',
    tenantId,
    missionId,
    createdAt,
    effectId: 'effect_s1',
    attemptNumber: 1,
    fence: 1,
    capabilityEnvelopeId: 'envelope_s1',
    adapterName: 'fixture',
    adapterVersion: '1',
    runnerDigest: digestA,
    requestDigest: digestA,
    idempotencyKeyHash: null,
    preRequestJournal: content,
    state: { status: 'prepared' }
  },
  'effect-receipt.v1': {
    schemaVersion: 1,
    kind: 'effect-receipt',
    id: 'receipt_s1',
    tenantId,
    missionId,
    createdAt,
    effectId: 'effect_s1',
    attemptId: 'effect_attempt_s1',
    fence: 1,
    adapterName: 'fixture',
    adapterVersion: '1',
    runnerDigest: digestA,
    requestDigest: digestA,
    idempotencyKeyHash: null,
    providerRequestId: null,
    providerResourceIds: ['legacy_patient'],
    status: 'applied',
    responseCategory: 'read-complete',
    beforeEvidence: null,
    afterEvidence: content,
    residualResources: [],
    rawResponse: content,
    signer: 'fixture-adapter',
    observedAt: laterAt
  },
  'target-observation.v1': {
    schemaVersion: 1,
    kind: 'target-observation',
    id: 'target_observation_s1',
    tenantId,
    missionId,
    createdAt,
    effectId: 'effect_s1',
    target,
    method: 'read-profile',
    identity: 'fixture-reader',
    observedState: { rows: 6 },
    observedVersion: '1',
    classification: 'applied',
    evidence: content,
    observedAt: laterAt,
    observedBy: actor
  },
  'recovery-disposition.v1': {
    schemaVersion: 1,
    kind: 'recovery-disposition',
    id: 'recovery_s1',
    tenantId,
    missionId,
    createdAt,
    effectId: 'effect_s1',
    triggeringAttemptId: 'effect_attempt_s1',
    receiptIds: ['receipt_s1'],
    observationIds: ['target_observation_s1'],
    action: 'wait',
    providerKeyStillValid: false,
    rationale: 'No recovery mutation is required.',
    residualRisk: [],
    selectedBy: actor
  },
  'compensation.v1': {
    schemaVersion: 1,
    kind: 'compensation',
    id: 'compensation_s1',
    tenantId,
    missionId,
    createdAt,
    forwardEffectId: 'effect_s1',
    compensationEffectId: 'effect_s2',
    restorationClaim: 'partial',
    preconditions: ['Forward effect remains current.'],
    knownResidualEffects: ['External observers may have seen the prior state.'],
    authorizedByPolicyDecisionId: 'policy_s1',
    evaluatedReceiptId: null
  }
}
